### ISSUE TITLE
Model confuses between similar faces sometimes

### ISSUE THREAD

**Issue by amlanmohanty1** [amlanmohanty1/Attendance-system-using-Face-Recognition#2]
Sometimes the model confuses between similar faces. 
For example- it confuses between me and my dad from web cam

**Comment by nishant1702** [comment]
Facing this issue. Please help me

Traceback (most recent call last):
  File "/Users/nishant/PycharmProjects/FaceRecognitionProject/AttendanceProject.py", line 46, in <module>
    encodeListKnown = findEncodings(images)
  File "/Users/nishant/PycharmProjects/FaceRecognitionProject/AttendanceProject.py", line 25, in findEncodings
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.2) /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-v0gme71y/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
